### PR TITLE
Add 'optionalChaining' to babylon-parser

### PR DESCRIPTION
**Pull request by chrishelgert**
As discussed in #183 this will be the first quick fix with adding `optionalChainging` to the plugin list.

### CODE REVIEW

**Comment by emilgoldsmith** [comment]
I don't think a test is needed for this, it's pretty simple :). I'll just merge it in, thanks for the contribution, it's always appreciated no matter the size :).

**Comment by emilgoldsmith** [comment]
It seems like we need to fix CI first as addressed in #190, then I'll merge it in right away

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Comment by rainboxx** [comment]
Could we have this in a release, please? 🙂

**Comment by emilgoldsmith** [comment]
Oh we never released this? Sorry if so, I'll try and remember this weekend, if I forget please feel free to remind me again

**Comment by emilgoldsmith** [comment]
@rainboxx published as 1.3.2

**Pull request merged**
