### PR TITLE
fix link to interpolation tagging in SC docs

### PR DESCRIPTION
**Pull request by WickyNilliams**

### CODE REVIEW

**Comment by emilgoldsmith** [comment]
Haha, thanks! That definitely wasn't the way to spell `tagging` ;)

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Comment by WickyNilliams** [comment]
Hey @mxstbr, that's an interesting approach! Do you ever have any problems with giving people write access so soon? I have a few open source projects that i'm struggling to maintain, and maybe this is a good approach for me!

**Comment by orta** [comment]
We've been doing it for a few years on [Danger](https://github.com/danger/) and [Moya](https://github.com/moya) and never had problems 👍

**Comment by WickyNilliams** [comment]
Cool. Thanks for letting me know!

**Comment by mxstbr** [comment]
> Do you ever have any problems with giving people write access so soon?

Nope :blush:

**Comment by WickyNilliams** [comment]
I just joined. I promise I won't cause problems 😄

**Pull request merged**
