### PR TITLE
Use babylon typescript parser

### PR DESCRIPTION
**Pull request by asvetliakov**
New babylon@7 understands and parses typescript by the same way as flow. This have following advantages over the ```typescript-eslint-parser```:

1. Babylon parser is backward compatible, new TS versions & language additions won't break it.
2. No need to maintain another dependency
3. No broken ```vscode-stylelint``` extension with unsupported TS versions, since ```typescript-eslint-parser``` emits warning in this case, breaking the extension.

### CODE REVIEW

**Comment by emilgoldsmith** [comment]
Hey @asvetliakov, great for noticing this! Don't you think a stable version will soon be released though and that we could wait for that instead of putting a beta product into our production branch?

**Comment by emilgoldsmith** [comment]
For your personal use if this is currently bothering you, you can of course just use this branch and use that as your stylelint processor :)

**Comment by asvetliakov** [comment]
>Hey @asvetliakov, great for noticing this! Don't you think a stable version will soon be released though and that we could wait for that instead of putting a beta product into our production branch?

From my expirience babylon/babel@7 is pretty stable and works very good - i'm using it with typescript over the pretty big project. There are few [issues](https://github.com/babel/babel/issues?q=is%3Aopen+is%3Aissue+label%3A%22area%3A+typescript%22) but nothing major.
For ```typescript-eslint-parser``` , i was unable to get it working with latest version of TS, even with manually installed version 9.
Also the ```typescript-eslint-parser``` produces warning for unsupported versions (```typescript@next```, ```typescript@rc```) and it's broken in this case in vscode-stylelint extension, since vscode text protocol doesn't expect it.

Your call here merge it now or later, for my personal use i have private npm server, so it's not bothering me too much.

**Comment by emilgoldsmith** [comment]
I'd like to hear opinions from @mxstbr and @ismay on this, but I think my gut feeling tells me let's wait until a stable release, if Babel aren't comfortable putting this in a production environment yet I don't feel like we should be recommending it.

If we end up not merging this then let's leave the code here though so if someone is in a similar situation to you and wants to use this "at their own risk" they can use this branch.

**Comment by emilgoldsmith** [comment]
@exogen I'm afraid it still seems quite far away https://github.com/babel/babel/milestone/14. Feel free to help them out finish it faster though ;)

**Comment by existentialism** [comment]
Just chiming in, the milestone you linked to is our "release after 7.0" list, we're just one issue away from 7.0-rc.

Also, re: Babylon@7.0-beta, we've been using it in Prettier for months without issue :)

**Comment by asvetliakov** [comment]
@emilgoldsmith Updated

**Comment by emilgoldsmith** [comment]
@mxstbr no we need the package-lock right? And it's already there, it's what specifies the exact versions we're using, no? Or should we stop using it?

**Comment by asvetliakov** [comment]
@existentialism good catch, updated

**Comment by emilgoldsmith** [comment]
I wonder how the CI was passing with a wrong import that... must have been a dependency of another package?

**Comment by asvetliakov** [comment]
devDependencies specifies babel-cli v6 which has dependency for babel-traverse. That's why CI/test run didn't catch it

**Comment by emilgoldsmith** [comment]
I just checked it out locally and when I run `npm install` it removes about 1000 redundant lines from `package-lock.json` so I pushed that (went from 1400 lines changed to 240 or something like that). I'll merge it in when CI passes

**Comment by mxstbr** [comment]
Thank you so much for helping us improve styled-components! Based on our [Community Guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md) every person that has a PR of any kind merged is offered **an invitation to the styled-components organization**—that is you right now!

Should you accept, you'll get write access to the main repository. (and a fancy `styled-components` logo on your GitHub profile!) You'll be able to label and close issues, merge pull requests, create new branches, etc. We want you to help us out with those things, so don't be scared to do them! Make sure to read our [contribution and community guidelines](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md), which explains all of this in more detail. Of course, if you have any questions just let me know!

**Pull request merged**
