### PR TITLE
Use default syntax in tests and README example

### LINKED ISSUE #170: Remove `syntax: 'scss'` from config in docs and tests
Firstly, thank you for creating and maintaining this processor. I use it myself when working with styled-components.

I had a query about the `syntax: scss` property value pair in the [Setup section](https://github.com/styled-components/stylelint-processor-styled-components#setup) of the README. 

```js
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss"
}
```

Is that pair unique to this processor as I don't believe it is used in stylelint itself? I did a cursory scan of the code base here, but couldn't find where it was used.

### PR DESCRIPTION
**Pull request by jeddy3**
Closes #170

### CODE REVIEW

**Comment by jeddy3** [comment]
It looks like tests on node@4 are timing out. Are you able to restart them?

**Comment by emilgoldsmith** [comment]
Restarted! Thanks for the PR @jeddy3 !

**Comment by emilgoldsmith** [comment]
And just a reminder to whomever (might even be me ;) ) we should also enforce this on the website https://www.styled-components.com/docs/tooling#stylelint (just a simple PR to the website repo)

**Comment by jeddy3** [comment]
> let's just submit a PR to the website repo before we merge this in so we don't forget though.

I already knocked one up whilst working in this PR.

https://github.com/styled-components/styled-components-website/pull/241

**Comment by emilgoldsmith** [comment]
Perfect, you're on top of it all!

**Comment by emilgoldsmith** [comment]
I'll merge this as soon as we can get the damn CI to agree with passing haha

**Comment by emilgoldsmith** [comment]
This CI business is basically a joke by now lol, on first build it failed on node 4, next one on node 6, and now it fails on node 8, while they pass on the different builds, totally unreliabie :(, let's hope this one works, or I'll just have to ask @mxstbr to admin override merge it

**Pull request merged**
