### PR TITLE
use unique name for each wrapped selector

### PR DESCRIPTION
**Pull request by ramitos**

### CODE REVIEW

**Comment by mxstbr** [comment]
Is this necessary/does it fix anything? I haven't run into any trouble just using `.selector`...

**Comment by ramitos** [comment]
yes, it conflicts with https://github.com/primer/stylelint-config-primer/blob/master/index.js#L263

**Comment by ramitos** [comment]
@mxstbr incrementing selector is a simple and great idea, will do that!

**Comment by ramitos** [comment]
@mxstbr updated

**Comment by mxstbr** [comment]
This is great, thanks so much!

**Pull request merged**
