### PR TITLE
allow overriding import name

### PR DESCRIPTION
**Pull request by brettjurgens**
Hi!

this PR allows the user to override the import name (currently it's set to "default"). 

In our project we have a file that re-exports Styled with type parameters. The problem is that we use a named export instead of a default export.

### CODE REVIEW

**Comment by brettjurgens** [comment]
@chinesedfan can we merge this one too 😃

**Comment by chinesedfan** [comment]
@brettjurgens Done. Hope @emilgoldsmith or @mxstbr can publish a new version soon.

**Comment by emilgoldsmith** [comment]
But @chinesedfan you have publishing rights since a week ago or something like that, right?

**Comment by chinesedfan** [comment]
@emilgoldsmith Nope. We discussed, but no one granted permissions to me.

**Comment by chinesedfan** [comment]
@emilgoldsmith I login npmjs.com and confirmed. Before that, `npm owner ls` didn't list my account. That's why I thought I had no permissions. Thanks you guys!

**Comment by emilgoldsmith** [comment]
Awesome :)

**Pull request merged**
