### PR TITLE
Add newline between components' styles

### PR DESCRIPTION
**Pull request by geniusgordon**
#9 

declare extractedCSS as an array, use `.join('\n')` when return

### CODE REVIEW

**Comment by mxstbr** [comment]
Could you add some tests for the new behaviour please? Thank you!

**Comment by zalmoxisus** [comment]
Seems like twice decreasing the perf: https://jsperf.com/string-concat-via-array

**Comment by geniusgordon** [comment]
@mxstbr I don't know how to write tests for this, can't come up with an invalid testcase that produce the **rule-non-nested-empty-line-before** error. Any suggestions? Thank you!

**Comment by geniusgordon** [comment]
@zalmoxisus nice point though, never notice that perf issue

**Comment by mxstbr** [comment]
Sorry for the extremely slow response here, does this fix your issue? If so, why can't we add tests for it?

**Comment by geniusgordon** [comment]
It's ok now! I disabled `rule-empty-line-before` like the comment in #9 said

**Comment by EnoahNetzach** [comment]
I need this fix, so sorry if I opened another PR, but I'll cherry-pick these commits, so attribution should remain untouched.

**Pull request closed without merging**
